name: Terraform Infrastructure Deploy

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Action Terraform à exécuter'
        required: true
        type: choice
        options:
          - apply
          - destroy
        default: apply

jobs:
  terraform:
    name: Terraform ${{ github.event.inputs.terraform_action || 'Plan & Apply' }}
    runs-on: ubuntu-latest

    env:
      TF_VERSION: 1.6.0
      TF_CLOUD_ORG: forum-anonyme
      TF_CLOUD_WORKSPACE: aws-infra
      AWS_REGION: eu-central-1

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.terraform_action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: Terraform Destroy
        if: github.event.inputs.terraform_action == 'destroy'
        run: terraform destroy -auto-approve